### ISSUE TITLE
$output variable error

### ISSUE THREAD

**Issue by chadpriddle** [rfdy/imagemagick#3]
Trying to use this with laravel and get the following error even when using your stock example code:

ErrorException in Processor.php line 127:
Undefined variable: output

**Comment by lawsontyler** [comment]
@chadpriddle, could you try out the master branch?  I'm unable to reproduce it personally, but the change should fix it.

**Comment by chadpriddle** [comment]
I tried that and still get the same error.

Should the output be passed through the function like this?
$operation_builder = $im->getOperationBuilder($image, $output);

Obviously the function would have to be modified

**Comment by lawsontyler** [comment]
I'm not sure what you're referencing.  It seems completely different from the issue in your initial post.

Processor.php line 127 (130 in master) is `exec('which convert', $output, $status);`.  I assumed that you had the error because for some reason, exec() expects $output and $status to be references to variables that exist already.  I don't know how that relates to `$im->getOperationBuilder($image);`

Maybe it's dependent on your version of PHP? What version are you running?

**Comment by chadpriddle** [comment]
PHP 5.5.31

**Comment by lawsontyler** [comment]
I'm unable to reproduce this in PHP 5.5.31, 5.6.19, and 7.0.4

This is what I'm doing; please let me know if you're doing something different.

/home/myself/ImageMagick/test.php

``` PHP
<?php

use Rfd\ImageMagick\ImageMagick;
use Rfd\ImageMagick\CLI\Operation\Factory as OperationFactory;
use Rfd\ImageMagick\Image\File;
use Rfd\ImageMagick\Options\CommonOptions;

require __DIR__ . '/vendor/autoload.php';

$im = new ImageMagick(new OperationFactory());

$image = new File(__DIR__ . '/Tests/images/test_image_1.png');
$output = new File('/tmp/output.png');

$operation_builder = $im->getOperationBuilder($image);

$operation_builder
    ->resize()
    ->setWidth(320)
    ->setHeight(240)
    ->setGravity(CommonOptions::GRAVITY_CENTER)
    ->next()
    ->slice()
    ->setWidth(300)
    ->setHeight(200)
    ->setOffsetX(0)
    ->setOffsetY(0)
    ->setGravity(CommonOptions::GRAVITY_NORTHWEST)
    ->finish($output);
```

Run it with:

```
cd /home/myself/ImageMagick
php -d error_reporting=32767 test.php
```

Even with error_reporting at E_ALL I don't get any issues and /tmp/output.png exists.

**Comment by chadpriddle** [comment]
I had to enable exec in php.ini to get to this error

root@server [/home/devphox/public_html/twin/public]# php -d error_reporting=32767 image.php
which: no convert in (/usr/local/jdk/bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/X11R6/bin:/usr/local/puppet/sbin:/usr/local/puppet/bin:/root/bin)
which: no convert in (/usr/local/jdk/bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/X11R6/bin:/usr/local/puppet/sbin:/usr/local/puppet/bin:/root/bin)
sh: /convert: No such file or directory

Fatal error: Uncaught exception 'Rfd\ImageMagick\Exception\ImageMagickException' with message 'Error executing ImageMagick: 127' in /home/devphox/public_html/twin/vendor/rfd/imagemagick/CLI/Operation/Processor.php:95
Stack trace:
#0 /home/devphox/public_html/twin/vendor/rfd/imagemagick/Operation/Builder.php(55): Rfd\ImageMagick\CLI\Operation\Processor->processOperations(Object(Rfd\ImageMagick\Image\File), Object(Rfd\ImageMagick\Image\File))
#1 /home/devphox/public_html/twin/public/image.php(30): Rfd\ImageMagick\Operation\Builder->finish(Object(Rfd\ImageMagick\Image\File))
#2 {main}
  thrown in /home/devphox/public_html/twin/vendor/rfd/imagemagick/CLI/Operation/Processor.php on line 95

**Comment by lawsontyler** [comment]
Please install ImageMagick using your system's package manager (e.g. yum, apt-get).

**Comment by chadpriddle** [comment]
That did it. Thanks. I thought I installed it before. 

Does your script allow the ability to convert a .png to a .pdf?

**Comment by lawsontyler** [comment]
I'm glad it's working!

In theory, it should be able to do anything ImageMagick can do.  I've never actually attempted that, specifically.

In order to make ImageMagick do that, you'll have to make sure ghostscript is installed.

Here's what I would try:

``` php
<?php

use Rfd\ImageMagick\ImageMagick;
use Rfd\ImageMagick\CLI\Operation\Factory as OperationFactory;
use Rfd\ImageMagick\Image\File;
use Rfd\ImageMagick\Options\CommonOptions;

require __DIR__ . '/vendor/autoload.php';

$im = new ImageMagick(new OperationFactory());

$image = new File('/path/to/your/image.png');
$output = new File('/path/to/output/document.pdf');    // $output extension is PDF, not necessary...but nice.

$operation_builder = $im->getOperationBuilder($image);

$operation_builder
    ->convert('pdf')        // convert takes any option that ImageMagick understands; CommonOptions::FORMAT_* are just some easy constants.
    ->finish($output);
```

`convert -list format | grep -i PDF` will tell you if ImageMagick supports PDF reading/writing.

Unfortunately, looking at the code, there's no way to make a multi-page PDF document right now - it would require more than one Image as input...which isn't exactly something it knows how to do yet.

**Comment by chadpriddle** [comment]
Awesome. It worked as expected! Thanks for your help
